version: 0.2

env:
  variables:
    ECR_REPOSITORY: "akash"                 # Your ECR repository name
    AWS_ACCOUNT_ID: "381492133980"           # Your AWS Account ID
    AWS_REGION: "us-east-1"                  # Your AWS region
    IMAGE_TAG: "latest"                      # Docker image tag
    REPO_URI: "381492133980.dkr.ecr.us-east-1.amazonaws.com/akash"  # Full ECR repo URI

phases:
  install:
    runtime-versions:
      java: corretto17  # Ensure Java 17 is available
    commands:
      - echo "Installing Docker..."
      - yum install -y docker  # Install Docker
      - docker --version  # Verify Docker installation

  pre_build:
    commands:
      - echo "Retrieving authentication token for ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URI
      - echo "ECR login successful."

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t employee_detail .  # Build the Docker image
      - echo "Tagging Docker image for ECR..."
      - docker tag employee_detail:latest $REPO_URI:$IMAGE_TAG
      - echo "Pushing Docker image to ECR..."
      - docker push $REPO_URI:$IMAGE_TAG  # Push image to ECR

  

artifacts:
  files:
    - task-definition.json  # Include the task definition JSON file

cache:
  paths:
    - "~/.m2/**/*"  # Cache Maven dependencies to speed up builds
