version: 0.2

env:
  variables:
    ECR_REPOSITORY: "akash"
    AWS_ACCOUNT_ID: "381492133980"
    AWS_REGION: "us-east-1"
    IMAGE_TAG: "latest"
    REPO_URI: "381492133980.dkr.ecr.us-east-1.amazonaws.com/akash"
    DOCKER_HUB_IMAGE: "maven:3.9.4-eclipse-temurin-17"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Docker..."
      - yum install -y docker
      - echo "Starting Docker daemon..."
      - nohup dockerd &
      - timeout 15 sh -c "until docker info; do echo 'Waiting for Docker to start...'; sleep 1; done"
      - docker --version
      - echo "Installing Maven..."
      - yum install -y maven
      - mvn -version

  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URI
      - echo "ECR login successful."

  build:
    commands:
      - echo "Building the project with Maven..."
      - mvn clean package -DskipTests
      - echo "Building Docker image..."
      - docker build -t employee_details .
      - echo "Tagging Docker image for ECR..."
      - docker tag employee_details:latest $REPO_URI:$IMAGE_TAG
      - echo "Pushing Docker image to ECR..."
      - docker push $REPO_URI:$IMAGE_TAG

artifacts:
  files:
    - task-definition.json

cache:
  paths:
    - "/root/.m2/**/*"
